### ISSUE TITLE
initday.txt growing forever

### ISSUE THREAD

**Issue by umtauscher** [pcmvanveen/Ginlong-Solar-InfluxDB-MQTT#1]
High, First of all thank you very much for you work.
I am using it for some time now.
Today I found a little bug, that caused the listener to quit working.
It seems you forgot a seek(0) In line 100 of your script. This leed to initday.txt growing forever until python quits.
Thanks again.
Cheers

**Comment by pcmvanveen** [comment]
I update my script and now it is not growing anymore.
Thanks for your remark.

**Comment by umtauscher** [comment]
I'm, sorry, but the fix you implemeted won't fix anything.
As I see it, the seek(0) has to go into the else branch before writing the new value.
